class Data():
    RECTANGLE_SIDE_A = 3
    RECTANGLE_SIDE_B = 5
    INT = 8
    SQUARE_SIDE = 9
    CIRCLE_RADIUS = 7
    TRIANGLE_SIDE_A = 11
    TRIANGLE_SIDE_B = 15
    TRIANGLE_SIDE_C = 20
    TRIANGLE_SIDE_WRONG = 1
